CREATE TABLE IF NOT EXISTS PRODUCT_PRICING_DB.RAW.STATS_NZ_SELECTED_PRICE_INDEXES (
    SERIES_REFERENCE VARCHAR,
    PERIOD VARCHAR,
    DATA_VALUE NUMBER(18, 8),
    STATUS VARCHAR,
    UNITS VARCHAR,
    SUBJECT VARCHAR,
    GROUP_NAME VARCHAR,
    SERIES_TITLE_1 VARCHAR,
    SERIES_TITLE_2 VARCHAR,
    SERIES_TITLE_3 VARCHAR,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE VARCHAR
);